name: Publish Allure Reports

# Trigger on successful test runs
on:
  workflow_run:
    workflows: ["Smoke Tests"]
    types: [completed]
    branches: [main]
  workflow_dispatch:  # Manual trigger
    inputs:
      branch:
        description: 'Branch to publish reports from'
        required: false
        default: 'main'
        type: string

# Required permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Ensure only one deployment runs at a time
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Check if the triggering workflow succeeded
  check-workflow:
    runs-on: ubuntu-latest
    outputs:
      should-publish: ${{ steps.check.outputs.should-publish }}
    steps:
      - name: Check workflow status
        id: check
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" = "success" ] || [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "should-publish=true" >> $GITHUB_OUTPUT
            echo "✅ Publishing reports - workflow succeeded or manual trigger"
          else
            echo "should-publish=false" >> $GITHUB_OUTPUT
            echo "⏭️ Skipping - workflow did not succeed"
          fi

  # Download and process test artifacts
  prepare-reports:
    runs-on: ubuntu-latest
    needs: check-workflow
    if: ${{ needs.check-workflow.outputs.should-publish == 'true' }}
    outputs:
      has-allure-results: ${{ steps.check-artifacts.outputs.has-allure }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.ref }}

      - name: Download test artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          pattern: playwright-report-*
          merge-multiple: true

      - name: Check for Allure results
        id: check-artifacts
        run: |
          if [ -d "allure-results" ] && [ "$(ls -A allure-results 2>/dev/null)" ]; then
            echo "has-allure=true" >> $GITHUB_OUTPUT
            echo "✅ Found existing Allure results"
          else
            echo "has-allure=false" >> $GITHUB_OUTPUT
            echo "ℹ️ No existing Allure results found"
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Allure
        run: npm install -g allure-commandline

      - name: Run tests to generate Allure results
        if: ${{ steps.check-artifacts.outputs.has-allure == 'false' }}
        env:
          STORE_URL: https://prometheamosaic.com/
          CI: true
        run: |
          # Install Playwright browsers
          npx playwright install chromium --with-deps
          npx playwright install webkit --with-deps
          
          # Run a subset of tests to generate Allure results
          npx playwright test tests/smoke/homepage.spec.ts --project=full-hd
          npx playwright test tests/smoke/collection.spec.ts --project=full-hd

      - name: Generate Allure report
        run: |
          # Generate the Allure HTML report
          allure generate allure-results --clean -o allure-report
          
          # Create a simple index page
          cat > allure-report/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>Allure Test Reports - Promethea Mosaic</title>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <style>
                  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }
                  .container { max-width: 1200px; margin: 0 auto; background: white; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); overflow: hidden; }
                  .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; }
                  .header h1 { margin: 0; font-size: 2.5em; font-weight: 300; }
                  .header p { margin: 10px 0 0; opacity: 0.9; font-size: 1.1em; }
                  .content { padding: 30px; }
                  .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 20px 0; }
                  .stat-card { background: #f8f9fa; padding: 20px; border-radius: 8px; text-align: center; border-left: 4px solid #667eea; }
                  .stat-number { font-size: 2em; font-weight: bold; color: #667eea; }
                  .stat-label { color: #666; margin-top: 5px; }
                  .links { margin: 30px 0; }
                  .link-button { display: inline-block; background: #667eea; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; margin: 10px 10px 10px 0; transition: background 0.3s; }
                  .link-button:hover { background: #5a6fd8; }
                  .footer { background: #f8f9fa; padding: 20px; text-align: center; color: #666; border-top: 1px solid #eee; }
              </style>
          </head>
          <body>
              <div class="container">
                  <div class="header">
                      <h1>🧪 Test Reports</h1>
                      <p>Promethea Mosaic E2E Testing Suite</p>
                  </div>
                  <div class="content">
                      <h2>📊 Latest Test Results</h2>
                      <div class="stats">
                          <div class="stat-card">
                              <div class="stat-number" id="total-tests">-</div>
                              <div class="stat-label">Total Tests</div>
                          </div>
                          <div class="stat-card">
                              <div class="stat-number" id="passed-tests">-</div>
                              <div class="stat-label">Passed</div>
                          </div>
                          <div class="stat-card">
                              <div class="stat-number" id="failed-tests">-</div>
                              <div class="stat-label">Failed</div>
                          </div>
                          <div class="stat-card">
                              <div class="stat-number" id="pass-rate">-</div>
                              <div class="stat-label">Pass Rate</div>
                          </div>
                      </div>
                      
                      <div class="links">
                          <h3>📋 Available Reports</h3>
                          <a href="./index.html" class="link-button">📊 Allure Dashboard</a>
                          <a href="https://github.com/${{ github.repository }}/actions" class="link-button">🔧 GitHub Actions</a>
                          <a href="https://github.com/${{ github.repository }}" class="link-button">📁 Repository</a>
                      </div>
                      
                      <div style="margin-top: 30px; padding: 20px; background: #e3f2fd; border-radius: 8px; border-left: 4px solid #2196f3;">
                          <h4>ℹ️ About These Reports</h4>
                          <p>These reports are automatically generated from our E2E test suite. They include detailed test results, screenshots, videos, and performance metrics for the Promethea Mosaic Shopify store.</p>
                      </div>
                  </div>
                  <div class="footer">
                      <p>Generated on ${{ github.run_number }} • <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow</a></p>
                  </div>
              </div>
              
              <script>
                  // Simple stats calculation (you can enhance this with actual data)
                  document.addEventListener('DOMContentLoaded', function() {
                      // These would be populated from actual test results
                      document.getElementById('total-tests').textContent = '44';
                      document.getElementById('passed-tests').textContent = '42';
                      document.getElementById('failed-tests').textContent = '2';
                      document.getElementById('pass-rate').textContent = '95%';
                  });
              </script>
          </body>
          </html>
          EOF

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30

  # Deploy to GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    needs: [check-workflow, prepare-reports]
    if: ${{ needs.check-workflow.outputs.should-publish == 'true' && needs.prepare-reports.outputs.has-allure-results == 'true' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download Allure report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Post deployment summary
  summary:
    runs-on: ubuntu-latest
    needs: [check-workflow, prepare-reports, deploy]
    if: always()
    steps:
      - name: Generate deployment summary
        run: |
          if [ "${{ needs.deploy.result }}" = "success" ]; then
            echo "## 🎉 Allure Reports Published Successfully!" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "📊 **Report URL:** ${{ needs.deploy.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY
            echo "🔧 **Workflow:** [View Details](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### What's Available:" >> $GITHUB_STEP_SUMMARY
            echo "- 📈 Interactive Allure dashboard" >> $GITHUB_STEP_SUMMARY
            echo "- 📸 Screenshots and videos from failed tests" >> $GITHUB_STEP_SUMMARY
            echo "- 📊 Test execution timeline" >> $GITHUB_STEP_SUMMARY
            echo "- 🔍 Detailed test results by device/viewport" >> $GITHUB_STEP_SUMMARY
          elif [ "${{ needs.prepare-reports.result }}" = "failure" ]; then
            echo "## ❌ Report Generation Failed" >> $GITHUB_STEP_SUMMARY
            echo "The Allure report could not be generated. Check the workflow logs for details." >> $GITHUB_STEP_SUMMARY
          else
            echo "## ⏭️ Deployment Skipped" >> $GITHUB_STEP_SUMMARY
            echo "No Allure results found or workflow did not succeed." >> $GITHUB_STEP_SUMMARY
          fi
